version: '2'

services:
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: docker

    nginx:
        image: nginx:1.10.2
        ports:
            - 80:80
        restart: always
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ~/Projects:/code

    php:
        build: php
        expose:
            - 9000
        restart: always
        volumes:
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ~/Projects:/code
